{% set name = "FLORIS" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/FLORIS/archive/v{{ version }}.tar.gz
  sha256: c3fe4bb99de5eb61322accdf517472713edee275f17d8cb5c90ccb163e73bd40
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - coloredlogs
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - pytest
    - python
    - scipy
    - seaborn
    - scikit-learn

test:
  imports:
    - floris
    - floris.simulation
    - floris.tools

about:
  home: https://github.com/NREL/FLORIS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://floris.readthedocs.io
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
