{% set name = "FLORIS" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/NREL/FLORIS/archive/v{{ version }}.tar.gz
  sha256: 9c508bfd453f6e9af96fb23eb660807e95ad4bfa20cdfee451d857601f465d39
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - coloredlogs
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - pytest
    - python
    - scipy
    - seaborn
    - sklearn

test:
  imports:
    - floris
    - floris.simulation
    - floris.tools

about:
  home: "https://github.com/NREL/FLORIS"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "A controls-oriented engineering wake model."
  doc_url: "https://floris.readthedocs.io"
  dev_url: "https://github.com/NREL/FLORIS"

extra:
  recipe-maintainers:
    - rafmudaf
