{% set name = "floris" %}
{% set version = "4.6.4" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/floris/archive/v{{ version }}.tar.gz
  sha256: a30dc8f865fddc6ba5fca33f8bc4899da40f6a57cfc94e0f0822f68a411c5f6c
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs >=21.3
    - coloredlogs ~=15.0
    - matplotlib-base ~=3.0
    - numexpr ~=2.7
    - numpy ~=2.0
    - pandas ~=2.0
    - pathos ~=0.3
    - pyyaml ~=6.0
    - scipy ~=1.1
    - shapely ~=2.0

test:
  requires:
    - python {{ python_min }}
  #   - pip
  imports:
    - floris
  # has a bogus defined dep on sklearn instead of scikit-learn
  # commands:
  #   - pip check

about:
  home: https://github.com/NREL/FLORIS
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://nrel.github.io/floris
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
    - bayc
    - misi9170
