{% set name = "FLORIS" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/FLORIS/archive/v{{ version }}.tar.gz
  sha256: df03ca9e4479f551b611609e29e7bb7bdb32e3a85e2ec7c5a52ea1fe1400fcc5
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - coloredlogs
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - pytest
    - python
    - scipy
    - seaborn
    - scikit-learn

test:
  imports:
    - floris
    - floris.simulation
    - floris.tools

about:
  home: https://github.com/NREL/FLORIS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://floris.readthedocs.io
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
