{% set name = "floris" %}
{% set version = "3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FLORIS-{{ version }}.tar.gz
  sha256: 71c5b545ef37db1b6896ea71831b79e8c4963e2aac87a673fdeacb9e28c26038

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - coloredlogs >=10.0
    - matplotlib-base >=3
    - numpy >=1.16
    - pandas >=0.24
    - pyproj >=2.1
    - pytest >=4
    - scipy >=1.1
    - seaborn >=0.9
    - shapely >=1.7.1
    - scikit-learn

test:
  imports:
    - floris
    - floris.simulation
    - floris.tools
  # has a bogus defined dep on sklearn instead of scikit-learn
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/NREL/FLORIS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://floris.readthedocs.io
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
    - bayc
    - rhammond2
