{% set name = "floris" %}
{% set version = "4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/floris/archive/v{{ version }}.tar.gz
  sha256: e08c9d8aa0abba55c22be44d4e0f0ba6b0f2123d69ac7cdb7b92e4b1f5dfa758
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - attrs >=21.3
    - coloredlogs >=15.0
    - matplotlib-base >=3
    - numexpr >=2.7
    - numpy >=1.20
    - pandas >=2.0
    - pathos >=0.3
    - pyyaml >=6.0
    - scipy >=1.1
    - shapely >=2.0

test:
  imports:
    - floris
  commands:
    - pip check
  requires:
    # - pip
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/NREL/FLORIS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://nrel.github.io/floris
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
    - bayc
    - misi9170
