{% set name = "floris" %}
{% set version = "4.2.2" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/floris/archive/v{{ version }}.tar.gz
  sha256: 7e705be7dee3b6100165d797c2aaf89bb8ba748320b01cdff0f60662ad7831b6
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs >=21.3
    - coloredlogs >=15.0
    - matplotlib-base >=3
    - numexpr >=2.7
    - numpy >=1.20
    - pandas >=2.0
    - pathos >=0.3
    - pyyaml >=6.0
    - scipy >=1.1
    - shapely >=2.0

test:
  requires:
    - python {{ python_min }}
    - pytest
  imports:
    - floris
  commands:
    - pip check
    - pytest tests
  source_files:
    - floris/floris/turbine_library/iea_15MW_multi_dim_Tp_Hs.csv
    - examples/examples_wind_resource_grid/wrg_example.wrg
    - tests

about:
  home: https://github.com/NREL/FLORIS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A controls-oriented engineering wake model.
  doc_url: https://nrel.github.io/floris
  dev_url: https://github.com/NREL/FLORIS

extra:
  recipe-maintainers:
    - rafmudaf
    - bayc
    - misi9170
